package io.freeboot.generators;

import io.freeboot.generators.models.*;

public class ServiceTemplate
{
  protected static String nl;
  public static synchronized ServiceTemplate create(String lineSeparator)
  {
    nl = lineSeparator;
    ServiceTemplate result = new ServiceTemplate();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = " ";
  protected final String TEXT_2 = " " + NL + "package ";
  protected final String TEXT_3 = ".services;" + NL + "" + NL + "import org.springframework.beans.factory.annotation.Autowired;" + NL + "import org.springframework.stereotype.Service;" + NL + "" + NL + "import ";
  protected final String TEXT_4 = ".";
  protected final String TEXT_5 = ";" + NL + "import ";
  protected final String TEXT_6 = ".repositories.";
  protected final String TEXT_7 = "Repository;" + NL + "" + NL + "@Service" + NL + "public class ";
  protected final String TEXT_8 = "Service implements I";
  protected final String TEXT_9 = "Service {" + NL + "" + NL + "\t@Autowired" + NL + "\tprivate ";
  protected final String TEXT_10 = "Repository ";
  protected final String TEXT_11 = "Repo;" + NL + "\t" + NL + "\t@Override" + NL + "\tpublic ";
  protected final String TEXT_12 = " get";
  protected final String TEXT_13 = "ById(Integer id) {" + NL + "\t\treturn ";
  protected final String TEXT_14 = "Repo.findOne(id);" + NL + "\t}" + NL + "" + NL + "\t@Override" + NL + "\tpublic Iterable< ";
  protected final String TEXT_15 = " > getAll";
  protected final String TEXT_16 = "() {" + NL + "\t\treturn ";
  protected final String TEXT_17 = "Repo.findAll();" + NL + "\t}" + NL + "\t" + NL + "\t@Override" + NL + "\tpublic ";
  protected final String TEXT_18 = " create";
  protected final String TEXT_19 = "(";
  protected final String TEXT_20 = " ";
  protected final String TEXT_21 = ") {" + NL + "\t\treturn ";
  protected final String TEXT_22 = "Repo.save(";
  protected final String TEXT_23 = ");" + NL + "\t}" + NL + "\t" + NL + "\t@Override" + NL + "\tpublic Iterable< ";
  protected final String TEXT_24 = " > create";
  protected final String TEXT_25 = "(Iterable< ";
  protected final String TEXT_26 = " > ";
  protected final String TEXT_27 = ") {" + NL + "\t\treturn ";
  protected final String TEXT_28 = "Repo.save(";
  protected final String TEXT_29 = ");" + NL + "\t}" + NL + "\t" + NL + "\t@Override" + NL + "\tpublic boolean ";
  protected final String TEXT_30 = "Exists(Integer id) {" + NL + "\t\treturn ";
  protected final String TEXT_31 = "Repo.exists(id);" + NL + "\t}" + NL + "\t" + NL + "\t@Override" + NL + "\tpublic long ";
  protected final String TEXT_32 = "Count() {" + NL + "\t\treturn ";
  protected final String TEXT_33 = "Repo.count();" + NL + "\t}" + NL + "\t" + NL + "\t@Override" + NL + "\tpublic void delete";
  protected final String TEXT_34 = "(Integer id) {" + NL + "\t\t";
  protected final String TEXT_35 = "Repo.delete(id);" + NL + "\t}" + NL + "\t" + NL + "\t@Override" + NL + "\tpublic void delete";
  protected final String TEXT_36 = "(";
  protected final String TEXT_37 = " ";
  protected final String TEXT_38 = ") {" + NL + "\t\t";
  protected final String TEXT_39 = "Repo.delete(";
  protected final String TEXT_40 = ");" + NL + "\t}" + NL + "\t" + NL + "\t@Override" + NL + "\tpublic void delete";
  protected final String TEXT_41 = "(Iterable< ";
  protected final String TEXT_42 = " > ";
  protected final String TEXT_43 = ") {" + NL + "\t\t";
  protected final String TEXT_44 = "Repo.delete(";
  protected final String TEXT_45 = ");" + NL + "\t}" + NL + "\t" + NL + "}";
  protected final String TEXT_46 = NL;

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    stringBuffer.append(TEXT_1);
     ServiceModel model = (ServiceModel) argument; 
   String className = model.getClassRoot();
   String lowerClass = model.getClassRootCamelCase();
 
    stringBuffer.append(TEXT_2);
    stringBuffer.append(model.getPackageRoot());
    stringBuffer.append(TEXT_3);
    stringBuffer.append(model.getPackageRoot());
    stringBuffer.append(TEXT_4);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_5);
    stringBuffer.append(model.getPackageRoot());
    stringBuffer.append(TEXT_6);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_8);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_9);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_10);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_11);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_12);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_13);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_14);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_15);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_16);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_17);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_18);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_19);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_20);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_21);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_22);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_23);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_24);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_25);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_26);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_27);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_28);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_29);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_30);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_31);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_32);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_33);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_34);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_35);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_36);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_37);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_38);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_39);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_40);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_41);
    stringBuffer.append(className);
    stringBuffer.append(TEXT_42);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_43);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_44);
    stringBuffer.append(lowerClass);
    stringBuffer.append(TEXT_45);
    stringBuffer.append(TEXT_46);
    return stringBuffer.toString();
  }
}
